use hex::{
    anyhow,
    assets::Texture,
    glium::{
        texture::{MipmapsOption, RawImage2d},
        uniforms::{MagnifySamplerFilter, SamplerBehavior},
        Display,
    },
};
use std::io::Cursor;

pub fn load_texture(display: &Display, p: &[u8]) -> anyhow::Result<Texture> {
    let mut img = image::io::Reader::new(Cursor::new(p));

    img.set_format(image::ImageFormat::Png);

    let img = img.decode()?.to_rgba8();
    let dims = img.dimensions();
    let img = img.into_raw();

    Texture::new(
        display,
        RawImage2d::from_raw_rgba_reversed(&img, dims),
        MipmapsOption::AutoGeneratedMipmaps,
        SamplerBehavior {
            magnify_filter: MagnifySamplerFilter::Nearest,
            ..Default::default()
        },
    )
}
